let website =  require('./website/index.js');
let card =  require('./card/index.js');
let single =  require('./single/index.js');
let sign =  require('./sign/index.js');
let invitation =  require('./invitation/index.js');
exports.website = website;
exports.card = card;
exports.sign = sign;
exports.single = single;
exports.invitation = invitation;
exports.api_prefix ="http://mm.51wctt.com/Api/V1/";//http://localhost:2033/Api/V1/