let website =  require('./website/index.js');
let card =  require('./card/index.js');
let sign =  require('./sign/index.js');
let invitation =  require('./invitation/index.js');
exports.website = website;
exports.card = card;
exports.sign = sign;
exports.invitation = invitation;
exports.api_prefix ="http://192.168.0.103:1024/Api/V1/";//http://localhost:2033/Api/V1/